/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    kotlin("plugin.lombok") version "2.2.20"
    id("io.freefair.lombok") version "8.14.2"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.commons.codec.commons.codec)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.org.apache.commons.commons.text)
    api(libs.com.squareup.retrofit2.retrofit)
    api(libs.com.squareup.retrofit2.converter.jackson)
    api(libs.com.squareup.okhttp3.okhttp)
    api(libs.com.squareup.okhttp3.logging.interceptor)
    api(libs.com.squareup.okio.okio)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.org.slf4j.slf4j.api)
    api(libs.ch.qos.logback.logback.classic)
    api(libs.org.jetbrains.annotations)
    api(libs.org.java.websocket.java.websocket)
    api(libs.org.json.json)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.mockito.mockito.core)
    compileOnly(libs.org.projectlombok.lombok)
}

group = "io.github.wuhewuhe"
version = "1.2.8-yc3"
description = "bybit-java-api"
java.sourceCompatibility = JavaVersion.VERSION_11

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
